- name:  Install Docker
  hosts: all
  become: yes

  tasks:
    - name: Update apt packgaes
      apt:
        update_cache:yes

    - name:  Install Docker
      apt:
        name:  docker.io
        state: present 

    - name: Start Docker
      service:
        name:  docker
        state: started
        enable: yes